[project]
name = "charformer-jax"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jax[cuda12]>=0.7.0",
    "wandb>=0.21.0",
]
